# Server port
server.port=8080

# H2 Database Connection
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Enable H2 Console to view the database in the browser (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Hibernate/JPA Configuration
# update: automatically updates the database schema based on your entities
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console for learning purposes
spring.jpa.show-sql=true


//spring.application.name=demo
